# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "GoldFynch: e-discovery, simplified."
email: info@goldfynch.com
description: > # this means to ignore newlines until "baseurl:"
    GoldFynch is a powerful, easy-to-use, and incredibly affordable e-discovery platform for lawyers. Signing up is fast and free (it takes just minutes), so you can get to work immediately. GoldFynch is simple and intuitive: just drag-and-drop files into the GoldFynch app in your web browser to start searching, tagging and producing documents. Your files are secured on our cloud, with bank-grade encryption, so you don't need to install software. Pricing is transparent (no hidden fees or locked features), fixed, up-front, and 1/10th that of the industry standard. GoldFynch is hassle-free e-discovery, for less.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goldfynch.com" # the base hostname & protocol for your site

gems:
  - jekyll-sitemap
  - jekyll-paginate

# Build settings
markdown: kramdown
paginate: 5
permalink: /blog/:year/:month/:day/:title.html
